// Code generated by protoc-gen-go.
// source: gift/gift.proto
// DO NOT EDIT!

/*
Package gift is a generated protocol buffer package.

It is generated from these files:
	gift/gift.proto

It has these top-level messages:
	GiftID
	Page
	SendGift
	Status
	GiftInfo
	Gifts
*/
package gift

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GiftID struct {
	GiftID string `protobuf:"bytes,1,opt,name=giftID" json:"giftID,omitempty"`
}

func (m *GiftID) Reset()                    { *m = GiftID{} }
func (m *GiftID) String() string            { return proto.CompactTextString(m) }
func (*GiftID) ProtoMessage()               {}
func (*GiftID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Page struct {
	Num  int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SendGift struct {
	GiftID      string `protobuf:"bytes,1,opt,name=giftID" json:"giftID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	ToUserID    string `protobuf:"bytes,3,opt,name=toUserID" json:"toUserID,omitempty"`
	BroadcastID string `protobuf:"bytes,4,opt,name=broadcastID" json:"broadcastID,omitempty"`
	MsgID       string `protobuf:"bytes,5,opt,name=msgID" json:"msgID,omitempty"`
	Number      int32  `protobuf:"varint,6,opt,name=number" json:"number,omitempty"`
}

func (m *SendGift) Reset()                    { *m = SendGift{} }
func (m *SendGift) String() string            { return proto.CompactTextString(m) }
func (*SendGift) ProtoMessage()               {}
func (*SendGift) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Status struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	MsgID   string `protobuf:"bytes,2,opt,name=msgID" json:"msgID,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GiftInfo struct {
	GiftID    string `protobuf:"bytes,1,opt,name=giftID" json:"giftID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Image     string `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	SnowBall  uint32 `protobuf:"varint,4,opt,name=snowBall" json:"snowBall,omitempty"`
	SnowFlake uint32 `protobuf:"varint,5,opt,name=snowFlake" json:"snowFlake,omitempty"`
	Combo     int32  `protobuf:"varint,6,opt,name=combo" json:"combo,omitempty"`
}

func (m *GiftInfo) Reset()                    { *m = GiftInfo{} }
func (m *GiftInfo) String() string            { return proto.CompactTextString(m) }
func (*GiftInfo) ProtoMessage()               {}
func (*GiftInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Gifts struct {
	List []*GiftInfo `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *Gifts) Reset()                    { *m = Gifts{} }
func (m *Gifts) String() string            { return proto.CompactTextString(m) }
func (*Gifts) ProtoMessage()               {}
func (*Gifts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Gifts) GetList() []*GiftInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*GiftID)(nil), "gift.GiftID")
	proto.RegisterType((*Page)(nil), "gift.Page")
	proto.RegisterType((*SendGift)(nil), "gift.SendGift")
	proto.RegisterType((*Status)(nil), "gift.Status")
	proto.RegisterType((*GiftInfo)(nil), "gift.GiftInfo")
	proto.RegisterType((*Gifts)(nil), "gift.Gifts")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Gift service

type GiftClient interface {
	Info(ctx context.Context, in *GiftID, opts ...grpc.CallOption) (*GiftInfo, error)
	List(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Gifts, error)
	Send(ctx context.Context, in *SendGift, opts ...grpc.CallOption) (*Status, error)
	Broadcast(ctx context.Context, in *SendGift, opts ...grpc.CallOption) (*Status, error)
}

type giftClient struct {
	cc *grpc.ClientConn
}

func NewGiftClient(cc *grpc.ClientConn) GiftClient {
	return &giftClient{cc}
}

func (c *giftClient) Info(ctx context.Context, in *GiftID, opts ...grpc.CallOption) (*GiftInfo, error) {
	out := new(GiftInfo)
	err := grpc.Invoke(ctx, "/gift.Gift/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftClient) List(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Gifts, error) {
	out := new(Gifts)
	err := grpc.Invoke(ctx, "/gift.Gift/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftClient) Send(ctx context.Context, in *SendGift, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/gift.Gift/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftClient) Broadcast(ctx context.Context, in *SendGift, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/gift.Gift/Broadcast", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gift service

type GiftServer interface {
	Info(context.Context, *GiftID) (*GiftInfo, error)
	List(context.Context, *Page) (*Gifts, error)
	Send(context.Context, *SendGift) (*Status, error)
	Broadcast(context.Context, *SendGift) (*Status, error)
}

func RegisterGiftServer(s *grpc.Server, srv GiftServer) {
	s.RegisterService(&_Gift_serviceDesc, srv)
}

func _Gift_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiftID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gift.Gift/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServer).Info(ctx, req.(*GiftID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gift_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gift.Gift/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServer).List(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gift_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGift)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gift.Gift/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServer).Send(ctx, req.(*SendGift))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gift_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGift)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gift.Gift/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServer).Broadcast(ctx, req.(*SendGift))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gift_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gift.Gift",
	HandlerType: (*GiftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Gift_Info_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Gift_List_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Gift_Send_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _Gift_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("gift/gift.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0x41, 0xcb, 0xd3, 0x40,
	0x10, 0x6d, 0xda, 0x4d, 0x4c, 0xa6, 0x56, 0x65, 0x10, 0x09, 0xc1, 0x43, 0xdc, 0x83, 0x14, 0x2a,
	0x15, 0xea, 0xc5, 0x73, 0x09, 0x4a, 0xc1, 0x83, 0xa4, 0xf8, 0x03, 0x36, 0xe9, 0x36, 0x04, 0x93,
	0xac, 0x64, 0x37, 0x08, 0xfe, 0x16, 0xcf, 0xfd, 0x9d, 0xb2, 0x93, 0x4d, 0x5b, 0x84, 0xf2, 0x5d,
	0xc2, 0x7b, 0xf3, 0x76, 0x5e, 0xe6, 0xed, 0x0e, 0xbc, 0xac, 0xea, 0xb3, 0xf9, 0x68, 0x3f, 0xdb,
	0x5f, 0xbd, 0x32, 0x0a, 0x99, 0xc5, 0x3c, 0x85, 0xe0, 0x6b, 0x7d, 0x36, 0x87, 0x0c, 0xdf, 0x40,
	0x50, 0x11, 0x8a, 0xbd, 0xd4, 0x5b, 0x47, 0xb9, 0x63, 0xfc, 0x03, 0xb0, 0xef, 0xa2, 0x92, 0xf8,
	0x0a, 0x16, 0xdd, 0xd0, 0x92, 0xe8, 0xe7, 0x16, 0x22, 0x02, 0xd3, 0xf5, 0x1f, 0x19, 0xcf, 0xa9,
	0x44, 0x98, 0x5f, 0x3c, 0x08, 0x8f, 0xb2, 0x3b, 0x59, 0xd3, 0x47, 0x96, 0xb6, 0x3e, 0x68, 0xd9,
	0x1f, 0x32, 0x6a, 0x8d, 0x72, 0xc7, 0x30, 0x81, 0xd0, 0xa8, 0x1f, 0xa3, 0xb2, 0x20, 0xe5, 0xca,
	0x31, 0x85, 0x65, 0xd1, 0x2b, 0x71, 0x2a, 0x85, 0xb6, 0x86, 0x8c, 0xe4, 0xfb, 0x12, 0xbe, 0x06,
	0xbf, 0xd5, 0xd5, 0x21, 0x8b, 0x7d, 0xd2, 0x46, 0x62, 0xff, 0xd5, 0x0d, 0x6d, 0x21, 0xfb, 0x38,
	0xa0, 0x31, 0x1d, 0xe3, 0x9f, 0x21, 0x38, 0x1a, 0x61, 0x06, 0x8d, 0x31, 0x3c, 0xd3, 0x43, 0x59,
	0x4a, 0xad, 0x69, 0xcc, 0x30, 0x9f, 0xe8, 0xcd, 0x71, 0x7e, 0xe7, 0xc8, 0xff, 0x7a, 0x10, 0xd2,
	0x9d, 0x75, 0x67, 0xf5, 0x30, 0x22, 0x02, 0xeb, 0x44, 0x2b, 0x5d, 0x27, 0x61, 0x6b, 0x57, 0xb7,
	0xa2, 0x92, 0x2e, 0xdb, 0x48, 0x6c, 0x68, 0xdd, 0xa9, 0xdf, 0x7b, 0xd1, 0x34, 0x94, 0x6a, 0x95,
	0x5f, 0x39, 0xbe, 0x85, 0xc8, 0xe2, 0x2f, 0x8d, 0xf8, 0x29, 0x29, 0xd6, 0x2a, 0xbf, 0x15, 0xac,
	0x5f, 0xa9, 0xda, 0x42, 0xb9, 0x64, 0x23, 0xe1, 0x1b, 0xf0, 0xed, 0x74, 0x1a, 0x39, 0xb0, 0xa6,
	0xd6, 0x26, 0xf6, 0xd2, 0xc5, 0x7a, 0xb9, 0x7b, 0xb1, 0xa5, 0xb7, 0x9f, 0x06, 0xcf, 0x49, 0xdb,
	0x5d, 0x3c, 0x60, 0xf4, 0x54, 0xef, 0x81, 0x51, 0x9e, 0xe7, 0x77, 0xc7, 0xb2, 0xe4, 0xbf, 0x26,
	0x3e, 0xc3, 0x77, 0xc0, 0xbe, 0xd5, 0xda, 0x20, 0x8c, 0x8a, 0xdd, 0x8c, 0x64, 0x79, 0x3b, 0xa5,
	0xf9, 0xcc, 0x5a, 0xd9, 0x0d, 0x40, 0xd7, 0x3c, 0x6d, 0x43, 0xe2, 0xac, 0xc7, 0x5b, 0xe7, 0x33,
	0xdc, 0x40, 0xb4, 0x9f, 0x9e, 0xef, 0xa9, 0xc3, 0x45, 0x40, 0x4b, 0xfb, 0xe9, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x21, 0x40, 0x55, 0x83, 0xc7, 0x02, 0x00, 0x00,
}
