// Code generated by "stringer -type MessageStatus"; DO NOT EDIT

package models

import "fmt"

const _MessageStatus_name = "CreatedRollbackedCommitted"

var _MessageStatus_index = [...]uint8{0, 7, 17, 26}

func (i MessageStatus) String() string {
	i -= 1
	if i < 0 || i >= MessageStatus(len(_MessageStatus_index)-1) {
		return fmt.Sprintf("MessageStatus(%d)", i+1)
	}
	return _MessageStatus_name[_MessageStatus_index[i]:_MessageStatus_index[i+1]]
}
