// Code generated by "stringer -type RequestFriendStatus"; DO NOT EDIT

package models

import "fmt"

const _RequestFriendStatus_name = "UnresponsedAgreedRefused"

var _RequestFriendStatus_index = [...]uint8{0, 11, 17, 24}

func (i RequestFriendStatus) String() string {
	if i < 0 || i >= RequestFriendStatus(len(_RequestFriendStatus_index)-1) {
		return fmt.Sprintf("RequestFriendStatus(%d)", i)
	}
	return _RequestFriendStatus_name[_RequestFriendStatus_index[i]:_RequestFriendStatus_index[i+1]]
}
