// Code generated by protoc-gen-go.
// source: coupon/coupon.proto
// DO NOT EDIT!

/*
Package coupon is a generated protocol buffer package.

It is generated from these files:
	coupon/coupon.proto

It has these top-level messages:
*/
package coupon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Coupon service

type CouponClient interface {
}

type couponClient struct {
	cc *grpc.ClientConn
}

func NewCouponClient(cc *grpc.ClientConn) CouponClient {
	return &couponClient{cc}
}

// Server API for Coupon service

type CouponServer interface {
}

func RegisterCouponServer(s *grpc.Server, srv CouponServer) {
	s.RegisterService(&_Coupon_serviceDesc, srv)
}

var _Coupon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.Coupon",
	HandlerType: (*CouponServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    fileDescriptor0,
}

func init() { proto.RegisterFile("coupon/coupon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 56 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0x2f, 0x2d,
	0xc8, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x11,
	0x07, 0x17, 0x9b, 0x33, 0x98, 0x95, 0xc4, 0x06, 0x96, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xc0, 0x76, 0x6f, 0x44, 0x2f, 0x00, 0x00, 0x00,
}
