// Code generated by protoc-gen-go.
// source: barrage/barrage.proto
// DO NOT EDIT!

/*
Package barrage is a generated protocol buffer package.

It is generated from these files:
	barrage/barrage.proto

It has these top-level messages:
	Broadcast
	Content
	Barrages
	Status
*/
package barrage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Broadcast struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *Broadcast) Reset()                    { *m = Broadcast{} }
func (m *Broadcast) String() string            { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()               {}
func (*Broadcast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Content struct {
	UserID   string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Text     string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	PubTime  int64  `protobuf:"varint,4,opt,name=pubTime" json:"pubTime,omitempty"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Barrages struct {
	List []*Content `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *Barrages) Reset()                    { *m = Barrages{} }
func (m *Barrages) String() string            { return proto.CompactTextString(m) }
func (*Barrages) ProtoMessage()               {}
func (*Barrages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Barrages) GetList() []*Content {
	if m != nil {
		return m.List
	}
	return nil
}

type Status struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Broadcast)(nil), "barrage.Broadcast")
	proto.RegisterType((*Content)(nil), "barrage.Content")
	proto.RegisterType((*Barrages)(nil), "barrage.Barrages")
	proto.RegisterType((*Status)(nil), "barrage.Status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Barrage service

type BarrageClient interface {
	Send(ctx context.Context, in *Content, opts ...grpc.CallOption) (*Status, error)
	RecentList(ctx context.Context, in *Broadcast, opts ...grpc.CallOption) (*Barrages, error)
}

type barrageClient struct {
	cc *grpc.ClientConn
}

func NewBarrageClient(cc *grpc.ClientConn) BarrageClient {
	return &barrageClient{cc}
}

func (c *barrageClient) Send(ctx context.Context, in *Content, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/barrage.Barrage/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barrageClient) RecentList(ctx context.Context, in *Broadcast, opts ...grpc.CallOption) (*Barrages, error) {
	out := new(Barrages)
	err := grpc.Invoke(ctx, "/barrage.Barrage/RecentList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Barrage service

type BarrageServer interface {
	Send(context.Context, *Content) (*Status, error)
	RecentList(context.Context, *Broadcast) (*Barrages, error)
}

func RegisterBarrageServer(s *grpc.Server, srv BarrageServer) {
	s.RegisterService(&_Barrage_serviceDesc, srv)
}

func _Barrage_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Content)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrageServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/barrage.Barrage/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrageServer).Send(ctx, req.(*Content))
	}
	return interceptor(ctx, in, info, handler)
}

func _Barrage_RecentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Broadcast)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrageServer).RecentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/barrage.Barrage/RecentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrageServer).RecentList(ctx, req.(*Broadcast))
	}
	return interceptor(ctx, in, info, handler)
}

var _Barrage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "barrage.Barrage",
	HandlerType: (*BarrageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Barrage_Send_Handler,
		},
		{
			MethodName: "RecentList",
			Handler:    _Barrage_RecentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("barrage/barrage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9b, 0x1f, 0x92, 0xf4, 0x0a, 0xfe, 0x5c, 0x50, 0x86, 0xb8, 0x09, 0x83, 0x8b, 0x80,
	0x50, 0xa5, 0xe2, 0x0b, 0xd4, 0x6e, 0x04, 0x57, 0xa9, 0x2f, 0x30, 0x49, 0x2f, 0x12, 0x6a, 0x26,
	0x65, 0xe6, 0x06, 0x7c, 0x7c, 0x71, 0x3a, 0x19, 0x17, 0x5d, 0x25, 0xdf, 0x39, 0xc3, 0xe1, 0xe3,
	0xc2, 0x6d, 0xab, 0x8c, 0x51, 0x5f, 0xf4, 0xe4, 0xbf, 0xab, 0xa3, 0x19, 0x79, 0xc4, 0xdc, 0xa3,
	0xbc, 0x87, 0xe5, 0xc6, 0x8c, 0x6a, 0xdf, 0x29, 0xcb, 0x78, 0x09, 0xf1, 0xfb, 0x56, 0x44, 0x55,
	0x54, 0x2f, 0x9b, 0xb8, 0xdf, 0xca, 0x03, 0xe4, 0x6f, 0xa3, 0x66, 0xd2, 0x8c, 0x77, 0x90, 0x4d,
	0x96, 0x4c, 0xa8, 0x3d, 0x61, 0x09, 0x85, 0xee, 0xbb, 0x83, 0x56, 0x03, 0x89, 0xd8, 0x35, 0x81,
	0x11, 0x21, 0x65, 0xfa, 0x61, 0x91, 0xb8, 0xdc, 0xfd, 0xa3, 0x80, 0xfc, 0x38, 0xb5, 0x9f, 0xfd,
	0x40, 0x22, 0xad, 0xa2, 0x3a, 0x69, 0x66, 0x94, 0xcf, 0x50, 0x6c, 0x4e, 0x52, 0x16, 0x1f, 0x20,
	0xfd, 0xee, 0x2d, 0x8b, 0xa8, 0x4a, 0xea, 0x8b, 0xf5, 0xf5, 0x6a, 0x96, 0xf7, 0x36, 0x8d, 0x6b,
	0xa5, 0x84, 0x6c, 0xc7, 0x8a, 0x27, 0xfb, 0xb7, 0x6a, 0xa7, 0xae, 0x23, 0x6b, 0x9d, 0x5e, 0xd1,
	0xcc, 0xb8, 0x1e, 0x20, 0xf7, 0xab, 0xf8, 0x08, 0xe9, 0x8e, 0xf4, 0x1e, 0xcf, 0xe6, 0xca, 0xab,
	0x90, 0x9c, 0xf6, 0xe4, 0x02, 0x5f, 0x01, 0x1a, 0xea, 0x48, 0xf3, 0x47, 0x6f, 0x19, 0x31, 0x3c,
	0x08, 0xc7, 0x2a, 0x6f, 0xfe, 0x33, 0xaf, 0x2d, 0x17, 0x6d, 0xe6, 0xce, 0xfb, 0xf2, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x81, 0x00, 0xc8, 0x77, 0x01, 0x00, 0x00,
}
