// Code generated by protoc-gen-go.
// source: client2server.proto
// DO NOT EDIT!

/*
Package gamevm is a generated protocol buffer package.

It is generated from these files:
	client2server.proto

It has these top-level messages:
	RequestVmIp
	ResponseVmIp
*/
package gamevm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// request
type RequestVmIp struct {
	GameId           *string `protobuf:"bytes,1,req,name=game_id" json:"game_id,omitempty"`
	Account          *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	PalyerIp         *uint32 `protobuf:"varint,3,req,name=palyer_ip" json:"palyer_ip,omitempty"`
	Key              *string `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	Sign             *string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestVmIp) Reset()                    { *m = RequestVmIp{} }
func (m *RequestVmIp) String() string            { return proto.CompactTextString(m) }
func (*RequestVmIp) ProtoMessage()               {}
func (*RequestVmIp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestVmIp) GetGameId() string {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return ""
}

func (m *RequestVmIp) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *RequestVmIp) GetPalyerIp() uint32 {
	if m != nil && m.PalyerIp != nil {
		return *m.PalyerIp
	}
	return 0
}

func (m *RequestVmIp) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *RequestVmIp) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

// response
type ResponseVmIp struct {
	VmIp             *uint32 `protobuf:"varint,1,req,name=vm_ip" json:"vm_ip,omitempty"`
	VmPort           *uint32 `protobuf:"varint,2,req,name=vm_port" json:"vm_port,omitempty"`
	GameId           *string `protobuf:"bytes,3,req,name=game_id" json:"game_id,omitempty"`
	Account          *string `protobuf:"bytes,4,req,name=account" json:"account,omitempty"`
	Key              *string `protobuf:"bytes,5,req,name=key" json:"key,omitempty"`
	Sign             *string `protobuf:"bytes,6,opt,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseVmIp) Reset()                    { *m = ResponseVmIp{} }
func (m *ResponseVmIp) String() string            { return proto.CompactTextString(m) }
func (*ResponseVmIp) ProtoMessage()               {}
func (*ResponseVmIp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseVmIp) GetVmIp() uint32 {
	if m != nil && m.VmIp != nil {
		return *m.VmIp
	}
	return 0
}

func (m *ResponseVmIp) GetVmPort() uint32 {
	if m != nil && m.VmPort != nil {
		return *m.VmPort
	}
	return 0
}

func (m *ResponseVmIp) GetGameId() string {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return ""
}

func (m *ResponseVmIp) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *ResponseVmIp) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ResponseVmIp) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestVmIp)(nil), "gamevm.request_vm_ip")
	proto.RegisterType((*ResponseVmIp)(nil), "gamevm.response_vm_ip")
}

func init() { proto.RegisterFile("client2server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8e, 0xbb, 0x8a, 0xc3, 0x30,
	0x14, 0x44, 0xf1, 0x73, 0xf1, 0xdd, 0xd5, 0x86, 0x38, 0x8d, 0x4a, 0xe3, 0xca, 0x55, 0x8a, 0xfc,
	0x90, 0x30, 0xce, 0xc5, 0x88, 0x58, 0x8f, 0x5c, 0xc9, 0x02, 0xff, 0x7d, 0x90, 0xec, 0x22, 0x49,
	0x37, 0xcc, 0xc0, 0x39, 0x03, 0x97, 0x69, 0x91, 0xa8, 0xfd, 0xcd, 0x21, 0x05, 0xa4, 0xab, 0x25,
	0xe3, 0x4d, 0x5b, 0xcf, 0xa3, 0xc2, 0xa0, 0x7a, 0x01, 0x8c, 0xf0, 0xb9, 0xa2, 0xf3, 0x22, 0x28,
	0x21, 0x6d, 0x7b, 0x82, 0x9f, 0x38, 0x09, 0x79, 0xe7, 0x59, 0x97, 0x0f, 0x4d, 0x2c, 0xc6, 0x69,
	0x32, 0xab, 0xf6, 0x3c, 0x4f, 0xc5, 0x19, 0x1a, 0x3b, 0x2e, 0x1b, 0x92, 0x90, 0x96, 0x17, 0x5d,
	0x3e, 0xb0, 0xf6, 0x17, 0x8a, 0x07, 0x6e, 0xbc, 0x4c, 0xfb, 0x1f, 0x94, 0x4e, 0xce, 0x9a, 0x57,
	0x5d, 0x36, 0x34, 0xbd, 0x82, 0x7f, 0x42, 0x67, 0x8d, 0x76, 0x78, 0x18, 0x18, 0x54, 0x29, 0x24,
	0x3e, 0x8b, 0xfc, 0xa0, 0x84, 0x35, 0xb4, 0xf3, 0xd9, 0xfb, 0x83, 0xe2, 0xfb, 0xc1, 0x6e, 0x38,
	0x74, 0xd5, 0x87, 0xae, 0x8e, 0xba, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x44, 0xfd, 0x0b,
	0xed, 0x00, 0x00, 0x00,
}
