// Code generated by protoc-gen-go.
// source: email/email.proto
// DO NOT EDIT!

/*
Package email is a generated protocol buffer package.

It is generated from these files:
	email/email.proto

It has these top-level messages:
	EmailCode
	Status
*/
package email

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailCode struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *EmailCode) Reset()                    { *m = EmailCode{} }
func (m *EmailCode) String() string            { return proto.CompactTextString(m) }
func (*EmailCode) ProtoMessage()               {}
func (*EmailCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*EmailCode)(nil), "email.EmailCode")
	proto.RegisterType((*Status)(nil), "email.Status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Email service

type EmailClient interface {
	Verify(ctx context.Context, in *EmailCode, opts ...grpc.CallOption) (*Status, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) Verify(ctx context.Context, in *EmailCode, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/email.Email/Verify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Email service

type EmailServer interface {
	Verify(context.Context, *EmailCode) (*Status, error)
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Verify(ctx, req.(*EmailCode))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "email.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _Email_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("email/email.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xcd, 0x4d, 0xcc,
	0xcc, 0xd1, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x29,
	0x17, 0xa7, 0x2b, 0x88, 0xe1, 0x9c, 0x9f, 0x92, 0x2a, 0x24, 0xc2, 0x05, 0x11, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x98,
	0xc0, 0x82, 0x60, 0xb6, 0x92, 0x12, 0x17, 0x5b, 0x70, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x90, 0x04,
	0x17, 0x7b, 0x71, 0x69, 0x72, 0x72, 0x6a, 0x71, 0x31, 0x58, 0x17, 0x47, 0x10, 0x8c, 0x6b, 0x64,
	0xc2, 0xc5, 0x0a, 0x36, 0x5a, 0x48, 0x9b, 0x8b, 0x2d, 0x2c, 0xb5, 0x28, 0x33, 0xad, 0x52, 0x48,
	0x40, 0x0f, 0xe2, 0x04, 0xb8, 0x95, 0x52, 0xbc, 0x50, 0x11, 0x88, 0x69, 0x4a, 0x0c, 0x49, 0x6c,
	0x60, 0xe7, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x54, 0x93, 0xc6, 0xb3, 0x00, 0x00,
	0x00,
}
