// Code generated by protoc-gen-go.
// source: upload/upload.proto
// DO NOT EDIT!

/*
Package upload is a generated protocol buffer package.

It is generated from these files:
	upload/upload.proto

It has these top-level messages:
	FileInfo
	Status
*/
package upload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileInfo struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=filePath" json:"filePath,omitempty"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*FileInfo)(nil), "upload.FileInfo")
	proto.RegisterType((*Status)(nil), "upload.Status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Upload service

type UploadClient interface {
	Send(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (*Status, error)
}

type uploadClient struct {
	cc *grpc.ClientConn
}

func NewUploadClient(cc *grpc.ClientConn) UploadClient {
	return &uploadClient{cc}
}

func (c *uploadClient) Send(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/upload.Upload/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Upload service

type UploadServer interface {
	Send(context.Context, *FileInfo) (*Status, error)
}

func RegisterUploadServer(s *grpc.Server, srv UploadServer) {
	s.RegisterService(&_Upload_serviceDesc, srv)
}

func _Upload_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/upload.Upload/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadServer).Send(ctx, req.(*FileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Upload_serviceDesc = grpc.ServiceDesc{
	ServiceName: "upload.Upload",
	HandlerType: (*UploadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Upload_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("upload/upload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0xc8, 0xc9,
	0x4f, 0x4c, 0xd1, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x13, 0x17, 0x87, 0x5b, 0x66, 0x4e, 0xaa, 0x67, 0x5e, 0x5a, 0xbe, 0x90, 0x14, 0x17, 0x47, 0x5a,
	0x66, 0x4e, 0x6a, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x0f,
	0x93, 0x0b, 0x48, 0x2c, 0xc9, 0x90, 0x60, 0x42, 0xc8, 0x81, 0xf8, 0x4a, 0x4a, 0x5c, 0x6c, 0xc1,
	0x25, 0x89, 0x25, 0xa5, 0xc5, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5,
	0x60, 0x03, 0x38, 0x82, 0x60, 0x5c, 0x23, 0x13, 0x2e, 0xb6, 0x50, 0xb0, 0x8d, 0x42, 0x5a, 0x5c,
	0x2c, 0xc1, 0xa9, 0x79, 0x29, 0x42, 0x02, 0x7a, 0x50, 0x07, 0xc1, 0xec, 0x97, 0xe2, 0x83, 0x89,
	0x40, 0x4c, 0x53, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5c,
	0xcd, 0x35, 0x00, 0xc3, 0x00, 0x00, 0x00,
}
