// Code generated by protoc-gen-go.
// source: profile/profile.proto
// DO NOT EDIT!

/*
Package profile is a generated protocol buffer package.

It is generated from these files:
	profile/profile.proto

It has these top-level messages:
	Ammount
	Message
	Status
	Request
	RequestID
*/
package profile

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ammount struct {
	UserID    string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	SnowFlake uint32 `protobuf:"varint,2,opt,name=snowFlake" json:"snowFlake,omitempty"`
	SnowBall  uint32 `protobuf:"varint,3,opt,name=snowBall" json:"snowBall,omitempty"`
	TypeID    uint32 `protobuf:"varint,4,opt,name=typeID" json:"typeID,omitempty"`
	TargetID  string `protobuf:"bytes,5,opt,name=targetID" json:"targetID,omitempty"`
}

func (m *Ammount) Reset()                    { *m = Ammount{} }
func (m *Ammount) String() string            { return proto.CompactTextString(m) }
func (*Ammount) ProtoMessage()               {}
func (*Ammount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	MsgID  string `protobuf:"bytes,1,opt,name=msgID" json:"msgID,omitempty"`
	UserID string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Status struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	MsgID   string `protobuf:"bytes,2,opt,name=msgID" json:"msgID,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Request struct {
	FromUserID string `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID   string `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RequestID struct {
	RequestID string `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
}

func (m *RequestID) Reset()                    { *m = RequestID{} }
func (m *RequestID) String() string            { return proto.CompactTextString(m) }
func (*RequestID) ProtoMessage()               {}
func (*RequestID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Ammount)(nil), "profile.Ammount")
	proto.RegisterType((*Message)(nil), "profile.Message")
	proto.RegisterType((*Status)(nil), "profile.Status")
	proto.RegisterType((*Request)(nil), "profile.Request")
	proto.RegisterType((*RequestID)(nil), "profile.RequestID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Profile service

type ProfileClient interface {
	Withdraw(ctx context.Context, in *Ammount, opts ...grpc.CallOption) (*Status, error)
	WithdrawRollback(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Status, error)
	WithdrawCommit(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Status, error)
	FriendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RequestID, error)
	FriendAgree(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*Status, error)
	FriendRefuse(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*Status, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) Withdraw(ctx context.Context, in *Ammount, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/profile.Profile/Withdraw", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) WithdrawRollback(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/profile.Profile/WithdrawRollback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) WithdrawCommit(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/profile.Profile/WithdrawCommit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) FriendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*RequestID, error) {
	out := new(RequestID)
	err := grpc.Invoke(ctx, "/profile.Profile/FriendRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) FriendAgree(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/profile.Profile/FriendAgree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) FriendRefuse(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/profile.Profile/FriendRefuse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profile service

type ProfileServer interface {
	Withdraw(context.Context, *Ammount) (*Status, error)
	WithdrawRollback(context.Context, *Message) (*Status, error)
	WithdrawCommit(context.Context, *Message) (*Status, error)
	FriendRequest(context.Context, *Request) (*RequestID, error)
	FriendAgree(context.Context, *RequestID) (*Status, error)
	FriendRefuse(context.Context, *RequestID) (*Status, error)
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ammount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Withdraw(ctx, req.(*Ammount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_WithdrawRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).WithdrawRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/WithdrawRollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).WithdrawRollback(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_WithdrawCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).WithdrawCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/WithdrawCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).WithdrawCommit(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_FriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).FriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/FriendRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).FriendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_FriendAgree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).FriendAgree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/FriendAgree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).FriendAgree(ctx, req.(*RequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_FriendRefuse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).FriendRefuse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/FriendRefuse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).FriendRefuse(ctx, req.(*RequestID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Withdraw",
			Handler:    _Profile_Withdraw_Handler,
		},
		{
			MethodName: "WithdrawRollback",
			Handler:    _Profile_WithdrawRollback_Handler,
		},
		{
			MethodName: "WithdrawCommit",
			Handler:    _Profile_WithdrawCommit_Handler,
		},
		{
			MethodName: "FriendRequest",
			Handler:    _Profile_FriendRequest_Handler,
		},
		{
			MethodName: "FriendAgree",
			Handler:    _Profile_FriendAgree_Handler,
		},
		{
			MethodName: "FriendRefuse",
			Handler:    _Profile_FriendRefuse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("profile/profile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x18, 0xc5, 0xd7, 0xbe, 0xef, 0xd6, 0xf5, 0xd1, 0xe9, 0x08, 0x2a, 0x65, 0x88, 0x8c, 0x5e, 0xcd,
	0x9b, 0x0d, 0xfc, 0xc3, 0xbc, 0x9d, 0x96, 0x41, 0x2f, 0x04, 0xa9, 0x0c, 0x2f, 0xa5, 0xdb, 0xb2,
	0x5a, 0xd6, 0x2c, 0x33, 0x49, 0x19, 0x7e, 0x0a, 0xbf, 0x9a, 0x1f, 0x49, 0x9a, 0x26, 0x6d, 0x90,
	0x5d, 0xec, 0xaa, 0xfc, 0x4e, 0x7a, 0x72, 0x4e, 0x9f, 0xa7, 0x70, 0xbe, 0x65, 0x74, 0x95, 0x66,
	0x78, 0xa4, 0x9e, 0xc3, 0x2d, 0xa3, 0x82, 0x22, 0x47, 0xa1, 0xff, 0x6d, 0x81, 0x33, 0x21, 0x84,
	0xe6, 0x1b, 0x81, 0x2e, 0xa0, 0x95, 0x73, 0xcc, 0xc2, 0xc0, 0xb3, 0xfa, 0xd6, 0xc0, 0x8d, 0x14,
	0xa1, 0x4b, 0x70, 0xf9, 0x86, 0xee, 0xa6, 0x59, 0xbc, 0xc6, 0x9e, 0xdd, 0xb7, 0x06, 0x9d, 0xa8,
	0x16, 0x50, 0x0f, 0xda, 0x05, 0x3c, 0xc6, 0x59, 0xe6, 0xfd, 0x93, 0x87, 0x15, 0x17, 0x37, 0x8a,
	0xaf, 0x2d, 0x0e, 0x03, 0xef, 0xbf, 0x3c, 0x51, 0x54, 0x78, 0x44, 0xcc, 0x12, 0x2c, 0xc2, 0xc0,
	0x6b, 0xca, 0xac, 0x8a, 0xfd, 0x31, 0x38, 0xcf, 0x98, 0xf3, 0x38, 0xc1, 0xe8, 0x0c, 0x9a, 0x84,
	0x27, 0x55, 0x9f, 0x12, 0x8c, 0x9a, 0xb6, 0x59, 0xd3, 0x7f, 0x80, 0xd6, 0xab, 0x88, 0x45, 0xce,
	0x91, 0x07, 0x0e, 0xcf, 0x17, 0x0b, 0xcc, 0xb9, 0x74, 0xb6, 0x23, 0x8d, 0xf5, 0x8d, 0xb6, 0x71,
	0xa3, 0xff, 0x0e, 0x4e, 0x84, 0x3f, 0x73, 0xcc, 0x05, 0xba, 0x02, 0x58, 0x31, 0x4a, 0x66, 0xe6,
	0x1c, 0x0c, 0x45, 0x36, 0xa7, 0x33, 0x33, 0xbe, 0xe2, 0x22, 0x96, 0x94, 0xcd, 0xe5, 0x20, 0xdc,
	0x48, 0xa3, 0x7f, 0x0d, 0xae, 0x0a, 0x28, 0xc7, 0xc9, 0x34, 0xa8, 0x84, 0x5a, 0xb8, 0xf9, 0xb1,
	0xc1, 0x79, 0x29, 0x97, 0x83, 0x46, 0xd0, 0x7e, 0x4b, 0xc5, 0xc7, 0x92, 0xc5, 0x3b, 0xd4, 0x1d,
	0xea, 0x0d, 0xaa, 0x75, 0xf5, 0x4e, 0x2b, 0xa5, 0xfc, 0x6c, 0xbf, 0x81, 0xc6, 0xd0, 0xd5, 0x86,
	0x88, 0x66, 0xd9, 0x3c, 0x5e, 0xac, 0x0d, 0xa3, 0x1a, 0xeb, 0x3e, 0xe3, 0x3d, 0x9c, 0x68, 0xe3,
	0x13, 0x25, 0x24, 0x15, 0x87, 0xd9, 0xc6, 0xd0, 0x99, 0xb2, 0x14, 0x6f, 0x96, 0x7a, 0x7c, 0xb5,
	0x4b, 0x29, 0x3d, 0xf4, 0x57, 0x09, 0x03, 0xbf, 0x81, 0xee, 0xe0, 0xa8, 0x34, 0x4e, 0x12, 0x86,
	0x31, 0xda, 0xf3, 0xd2, 0xfe, 0x96, 0xc7, 0x3a, 0x6e, 0x95, 0xf3, 0x43, 0x6d, 0xf3, 0x96, 0xfc,
	0xe7, 0x6f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xc5, 0x1b, 0xaf, 0x0c, 0x03, 0x00, 0x00,
}
