// Code generated by "stringer -type=GameStatus"; DO NOT EDIT

package models

import "fmt"

const _GameStatus_name = "UnvalidUploadedValidFailedPublishedDownAvailable"

var _GameStatus_index = [...]uint8{0, 7, 15, 26, 35, 39, 48}

func (i GameStatus) String() string {
	if i < 0 || i >= GameStatus(len(_GameStatus_index)-1) {
		return fmt.Sprintf("GameStatus(%d)", i)
	}
	return _GameStatus_name[_GameStatus_index[i]:_GameStatus_index[i+1]]
}
