// Code generated by protoc-gen-go.
// source: room/room.proto
// DO NOT EDIT!

/*
Package room is a generated protocol buffer package.

It is generated from these files:
	room/room.proto

It has these top-level messages:
	Broadcast
	Num
	CreateRequest
	ListRequest
	RoomInfo
	Rooms
	User
	Status
	BroadcastInfo
*/
package room

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Broadcast struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *Broadcast) Reset()                    { *m = Broadcast{} }
func (m *Broadcast) String() string            { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()               {}
func (*Broadcast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Num struct {
	BroadcastID string `protobuf:"bytes,1,opt,name=BroadcastID,json=broadcastID" json:"BroadcastID,omitempty"`
	Num         uint32 `protobuf:"varint,2,opt,name=Num,json=num" json:"Num,omitempty"`
}

func (m *Num) Reset()                    { *m = Num{} }
func (m *Num) String() string            { return proto.CompactTextString(m) }
func (*Num) ProtoMessage()               {}
func (*Num) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateRequest struct {
	UserID   string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Cover    string `protobuf:"bytes,4,opt,name=cover" json:"cover,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListRequest struct {
	Num    int32  `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Size   int32  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Search string `protobuf:"bytes,3,opt,name=search" json:"search,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RoomInfo struct {
	RoomID string `protobuf:"bytes,1,opt,name=roomID" json:"roomID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cover  string `protobuf:"bytes,3,opt,name=cover" json:"cover,omitempty"`
}

func (m *RoomInfo) Reset()                    { *m = RoomInfo{} }
func (m *RoomInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()               {}
func (*RoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Rooms struct {
	Rooms    []*RoomInfo `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	TotalNum int64       `protobuf:"varint,2,opt,name=totalNum" json:"totalNum,omitempty"`
}

func (m *Rooms) Reset()                    { *m = Rooms{} }
func (m *Rooms) String() string            { return proto.CompactTextString(m) }
func (*Rooms) ProtoMessage()               {}
func (*Rooms) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Rooms) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type User struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Status struct {
	RoomID  string `protobuf:"bytes,1,opt,name=roomID" json:"roomID,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BroadcastInfo struct {
	BroadcastID   string `protobuf:"bytes,1,opt,name=broadcastID" json:"broadcastID,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	StartTime     string `protobuf:"bytes,3,opt,name=startTime" json:"startTime,omitempty"`
	TotalAudience int64  `protobuf:"varint,4,opt,name=totalAudience" json:"totalAudience,omitempty"`
	Duration      int64  `protobuf:"varint,5,opt,name=duration" json:"duration,omitempty"`
}

func (m *BroadcastInfo) Reset()                    { *m = BroadcastInfo{} }
func (m *BroadcastInfo) String() string            { return proto.CompactTextString(m) }
func (*BroadcastInfo) ProtoMessage()               {}
func (*BroadcastInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Broadcast)(nil), "room.Broadcast")
	proto.RegisterType((*Num)(nil), "room.Num")
	proto.RegisterType((*CreateRequest)(nil), "room.CreateRequest")
	proto.RegisterType((*ListRequest)(nil), "room.ListRequest")
	proto.RegisterType((*RoomInfo)(nil), "room.RoomInfo")
	proto.RegisterType((*Rooms)(nil), "room.Rooms")
	proto.RegisterType((*User)(nil), "room.User")
	proto.RegisterType((*Status)(nil), "room.Status")
	proto.RegisterType((*BroadcastInfo)(nil), "room.BroadcastInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Room service

type RoomClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Status, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Rooms, error)
	Start(ctx context.Context, in *User, opts ...grpc.CallOption) (*BroadcastInfo, error)
	End(ctx context.Context, in *User, opts ...grpc.CallOption) (*BroadcastInfo, error)
	CurrentAudienceNum(ctx context.Context, in *Broadcast, opts ...grpc.CallOption) (*Num, error)
}

type roomClient struct {
	cc *grpc.ClientConn
}

func NewRoomClient(cc *grpc.ClientConn) RoomClient {
	return &roomClient{cc}
}

func (c *roomClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/room.Room/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Rooms, error) {
	out := new(Rooms)
	err := grpc.Invoke(ctx, "/room.Room/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) Start(ctx context.Context, in *User, opts ...grpc.CallOption) (*BroadcastInfo, error) {
	out := new(BroadcastInfo)
	err := grpc.Invoke(ctx, "/room.Room/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) End(ctx context.Context, in *User, opts ...grpc.CallOption) (*BroadcastInfo, error) {
	out := new(BroadcastInfo)
	err := grpc.Invoke(ctx, "/room.Room/End", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) CurrentAudienceNum(ctx context.Context, in *Broadcast, opts ...grpc.CallOption) (*Num, error) {
	out := new(Num)
	err := grpc.Invoke(ctx, "/room.Room/CurrentAudienceNum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Room service

type RoomServer interface {
	Create(context.Context, *CreateRequest) (*Status, error)
	List(context.Context, *ListRequest) (*Rooms, error)
	Start(context.Context, *User) (*BroadcastInfo, error)
	End(context.Context, *User) (*BroadcastInfo, error)
	CurrentAudienceNum(context.Context, *Broadcast) (*Num, error)
}

func RegisterRoomServer(s *grpc.Server, srv RoomServer) {
	s.RegisterService(&_Room_serviceDesc, srv)
}

func _Room_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/room.Room/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/room.Room/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/room.Room/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).Start(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/room.Room/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).End(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_CurrentAudienceNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Broadcast)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).CurrentAudienceNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/room.Room/CurrentAudienceNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).CurrentAudienceNum(ctx, req.(*Broadcast))
	}
	return interceptor(ctx, in, info, handler)
}

var _Room_serviceDesc = grpc.ServiceDesc{
	ServiceName: "room.Room",
	HandlerType: (*RoomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Room_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Room_List_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Room_Start_Handler,
		},
		{
			MethodName: "End",
			Handler:    _Room_End_Handler,
		},
		{
			MethodName: "CurrentAudienceNum",
			Handler:    _Room_CurrentAudienceNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("room/room.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x6d, 0x36, 0xc9, 0xb2, 0x99, 0xb0, 0x6d, 0x19, 0x10, 0x8a, 0x02, 0x42, 0x91, 0xd5, 0xc3,
	0x0a, 0x89, 0x22, 0x2d, 0x27, 0xb8, 0x41, 0xcb, 0x61, 0x45, 0xd5, 0x83, 0x0b, 0x3f, 0xc0, 0xcd,
	0x1a, 0x11, 0x89, 0xc4, 0xe0, 0x0f, 0x0e, 0xfc, 0x1f, 0x7e, 0x1c, 0xff, 0x02, 0x8d, 0x9d, 0x8f,
	0x5d, 0xb4, 0x95, 0x7a, 0x89, 0xfc, 0x5e, 0xc6, 0x9e, 0xe7, 0xf7, 0xc6, 0x70, 0xa2, 0x95, 0x6a,
	0x5f, 0xd3, 0xe7, 0xfc, 0x87, 0x56, 0x56, 0x61, 0x42, 0x6b, 0xf6, 0x0c, 0xb2, 0x0f, 0x5a, 0x89,
	0x6d, 0x2d, 0x8c, 0xc5, 0x63, 0x98, 0x6d, 0x2e, 0x8b, 0xa8, 0x8a, 0x56, 0x19, 0x9f, 0x35, 0x97,
	0xec, 0x2d, 0xc4, 0xd7, 0xae, 0xc5, 0x0a, 0xf2, 0xb1, 0x66, 0xfc, 0x9f, 0xdf, 0x4e, 0x14, 0x9e,
	0xfa, 0xc2, 0x62, 0x56, 0x45, 0xab, 0x25, 0x8f, 0x3b, 0xd7, 0xb2, 0x16, 0x96, 0x17, 0x5a, 0x0a,
	0x2b, 0xb9, 0xfc, 0xe9, 0xa4, 0xb1, 0xf8, 0x14, 0xe6, 0xce, 0x48, 0x3d, 0xee, 0xef, 0x11, 0x96,
	0xb0, 0xa0, 0xd5, 0xb5, 0x68, 0xa5, 0xdf, 0x9f, 0xf1, 0x11, 0x23, 0x42, 0xd2, 0x11, 0x1f, 0x7b,
	0xde, 0xaf, 0xf1, 0x09, 0xa4, 0xb5, 0xfa, 0x25, 0x75, 0x91, 0x78, 0x32, 0x00, 0xf6, 0x09, 0xf2,
	0xab, 0xc6, 0xd8, 0xa1, 0xd9, 0x29, 0x90, 0x08, 0xdf, 0x29, 0xf5, 0x7a, 0xe8, 0x28, 0xd3, 0xfc,
	0x0e, 0x2d, 0x52, 0xee, 0xd7, 0x24, 0xc9, 0x48, 0xa1, 0xeb, 0x6f, 0x7d, 0x83, 0x1e, 0xb1, 0x2b,
	0x58, 0x70, 0xa5, 0xda, 0x4d, 0xf7, 0x55, 0x51, 0x0d, 0xf9, 0x34, 0xc9, 0x0e, 0x68, 0x94, 0x36,
	0x3b, 0x24, 0x2d, 0xde, 0x95, 0xb6, 0x81, 0x94, 0x4e, 0x33, 0x78, 0x06, 0x29, 0x6d, 0x36, 0x45,
	0x54, 0xc5, 0xab, 0x7c, 0x7d, 0x7c, 0xee, 0xc3, 0x18, 0x3a, 0xf1, 0xf0, 0x93, 0xfc, 0xb0, 0xca,
	0x8a, 0xef, 0x83, 0x9f, 0x31, 0x1f, 0x31, 0x7b, 0x01, 0xc9, 0x17, 0x23, 0xf5, 0x5d, 0x5e, 0xb2,
	0x77, 0x30, 0xbf, 0xb1, 0xc2, 0x3a, 0x73, 0xa7, 0xec, 0x02, 0x1e, 0x18, 0x57, 0xd7, 0xd2, 0x18,
	0x7f, 0xf8, 0x82, 0x0f, 0x90, 0xfd, 0x89, 0x60, 0x39, 0xa5, 0x4c, 0x57, 0xaf, 0x60, 0x37, 0xe3,
	0x43, 0xb1, 0x1f, 0x32, 0xe1, 0x39, 0x64, 0xc6, 0x0a, 0x6d, 0x3f, 0x37, 0x63, 0x70, 0x13, 0x81,
	0x67, 0xb0, 0xf4, 0xb7, 0x79, 0xef, 0xb6, 0x8d, 0xec, 0x6a, 0xe9, 0x53, 0x8c, 0xf9, 0x3e, 0x49,
	0x1e, 0x6c, 0x9d, 0x16, 0xb6, 0x51, 0x5d, 0x91, 0x06, 0x0f, 0x06, 0xbc, 0xfe, 0x1b, 0x41, 0x42,
	0x9e, 0xe1, 0x2b, 0x98, 0x87, 0x09, 0xc3, 0xc7, 0xc1, 0xc9, 0xbd, 0x79, 0x2b, 0x1f, 0x06, 0x32,
	0xf8, 0xc1, 0x8e, 0x70, 0x05, 0x09, 0x4d, 0x08, 0x3e, 0x0a, 0xfc, 0xce, 0xb4, 0x94, 0xf9, 0x94,
	0x04, 0x55, 0xbe, 0x84, 0xf4, 0x86, 0x04, 0x23, 0x04, 0x9e, 0x2c, 0x2f, 0xfb, 0x1e, 0x7b, 0x0e,
	0xf9, 0x53, 0xe3, 0x8f, 0xdd, 0xf6, 0x3e, 0x95, 0x6b, 0xc0, 0x0b, 0xa7, 0xb5, 0xec, 0xec, 0x70,
	0x4d, 0x7a, 0x5a, 0x27, 0xff, 0x15, 0x97, 0x59, 0x20, 0x28, 0xed, 0xa3, 0xdb, 0xb9, 0x7f, 0xa9,
	0x6f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x5c, 0x17, 0x63, 0xbc, 0x03, 0x00, 0x00,
}
